"""Trinity Avatar motion service.

Streams SOMA-24 skeletal pose frames over WebSocket at 30+ fps, generated by
NVIDIA ARDY (autoregressive diffusion, needs a CUDA GPU) or by the bundled
procedural clip library when no GPU/weights are available.
"""

__version__ = "0.1.0"
